debug: true
server:
  port: 8888
  context-path: /
spring:
  datasource:
    name: springCloud-demo
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.126/mydb?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true

#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/hadesvip/springcloud-demo.git
#          search-paths: config
#          basedir: springcloud-demo
mybatis:
  type-aliases-package: com.bean
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml